name: Build and deploy
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin

      - name: Build
        run: go build -o dragonfly_exe -v .

      - name: Vet
        run: go vet ./...

      - name: Formatting
        run: test -z $(go fmt ./...)

      - name: Staticcheck
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          GOBIN=$PWD/bin go install honnef.co/go/tools/cmd/staticcheck
          ./bin/staticcheck ./...

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin

      - name: Build
        run: go build -o dragonfly_exe -v .

      - name: Set SSH info
        env:
          HOST: ${{ secrets.HOST }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Stop server
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa $HOST screen -d -R -S dragonfly -X stuff '^C'
          ssh -i ~/.ssh/id_rsa $HOST rm -f dragonfly_exe

      - name: Transfer executable
        env:
          HOST: ${{ secrets.HOST }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          scp -i ~/.ssh/id_rsa dragonfly_exe $HOST:/home/dragonfly_exe

      - name: Restart server
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa $HOST "screen -d -R -S dragonfly -X stuff './dragonfly_exe\n'"
